# Homework 5: Data visualization

**YData — Fall 2026**

Welcome to the fifth homework! 

In this homework you practice visualizing data. You will get a little more practice manipulating DataFrames which is one of the important data science skills.  Please complete this notebook by filling in the cells provided. 

**Deadline:** This assignment is due **Monday October 19th at 11pm**, before the October recess. You can turn in the assignment up to 24 hours late for 90% credit (after that, the homework will only be accepted with a dean's excuse). 

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged. **You are not allowed to use chatGPT to answer any questions on the homework**. If your answers include code that we have not discussed in class that is copied from chatGPT, this will be considered a violation of academic dishonesty and will face disciplinary action.

**There is one exception, and it is only in question 2.5.** That question asks you to stop the axis labels overlapping and to size the figure sensibly. For *that cosmetic part only*, you may look things up with Google or chatGPT. The exception does not reach any other question, and it does not reach the rest of 1.5 either: the bar plot, the pie chart, their labels and the DataFrame behind them must be your own work, using what we covered in class.

You should start early so that you have time to get help if you're stuck. The drop-in office hours schedule can be found on Canvas.  You can also post questions or start discussions on Ed Discussion.

## Getting started

In order to complete the homework, it is necessary to download a few files. Please run the code below **only once** to download data needed to complete the homework. To run the code, click in the cell below and press the play button (or press shift-enter).

In [ ]:
# Please run this code once to download the files you will need to complete the homework 

import YData 

YData.download.download_data("gapminder_data.csv")
YData.download.download_data("daily_bike_totals.csv")

The file `gapminder_data.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.
The file `daily_bike_totals.csv` already exists.
If you would like to download a new copy of the file, please rename the existing copy of the file.

<div style="page-break-after: always;"></div>

## 1. Finding an interesting visualization to share

Instead of doing a quote and reaction this week, the opening homework activity is to find an interesting data visualization that you can share with the class. 

Please search the Internet (or scan a picture from a book or magazine) to find an interesting data visualization. Once you have found the visualization, put a link to it below along with a brief description of why you found the visualization interesting. 

Also, on the homework 5 reflection quiz on Canvas, please: 
1. Upload your image
2. Write the URL of where you found the image (or name the source if the image is not from the Internet)
3. Copy your description of why you think it is interesting

**Question 1.1 (5 points)**  Please write a link to your image and why you find it interesting. Also be sure to upload your image to the homework 5 reflection on Canvas.

*Link to the image:*  ...

Why you find it interesting: ...

In [ ]:
# This cell imports functions from packages we will use below.
# Please run it each time you load the Jupyter notebook

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

<div style="page-break-after: always;"></div>

## 2. Gapminder data

As we discussed in class, [according to Friendly](https://www.datavis.ca/papers/hbook.pdf), data visualization is currently undergoing a "rebirth". This was particularly true around ~2010, as exemplified by Hans Rosling's Ted Talk and other videos where he visualized the progress the world is making towards people becoming healthier and wealthier. In this first set of exercises, we will create some visualizations of Hans Rosling's "Gapminder" data. 

For all exercises, be sure to label your plots appropriately (i.e., put axes labels on all plots).

**Question 2.1 (4 points)** To start, [please watch this video](https://www.youtube.com/watch?v=jbkSRLYSojo) by Hans Rosling. Then in the space below, write down a one-word reaction to the video. Also, copy your one-word reaction to the homework 5 reflection quiz on Canvas.

**Please write your one word reaction here**. Also copy your one-word reaction to the homework 5 Canvas reflection survey.

<font color='red'> **Answer**


</font>

**Question 2.2 (2 points)**  Let's now begin to analyze and visualize the gapminder data. 

The cell below loads the Gapminder data and prints the first three rows. The columns of this DataFrame are: 

- `country`: The name of the country
- `year`: The year that the measurements correspond to
- `pop`: Population size of a country
- `continent`: Continent name that the country is in
- `lifeExp`: The average life expectancy 
- `gdpPercap`: The GDP per capita for that country (which is a measure of wealth) 

Please add to the code in cell below one line of code that prints the data types (i.e., the `dtypes`) of the columns in this DataFrame.

In [ ]:
gapminder = pd.read_csv("gapminder_data.csv")
gapminder.head(3)

       country  year         pop continent  lifeExp   gdpPercap
0  Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1  Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2  Afghanistan  1962  10267083.0      Asia   31.997  853.100710

In [ ]:
# Answer
# add a line of code to print the dtypes of the columns here
...

**Question 2.3 (4 points)**: 

For all our visualizations in this first part of the homework, let's only look at data from 2007. To do this, please create a DataFrame named `gapminder_2007` which has data from all the countries for only the year 2007. Also print out how many rows this DataFrame has and show the first 3 rows of this DataFrame.

In [ ]:
# Answer

# get only data from 2007
gapminder_2007 = ...

**Question 2.4 (4 points)**: Before we dive into our first visualization of the data, please create a DataFrame called `continent_count` that has the number of countries in each continent. In particular, the `continent_count` should have two columns which are:

1. A column called `continent` that contains the names of the continents.
2. A column called `num_countries` which has a count of how many countries are in each continent. 

As always, be sure to print the table to show your work.  

Hint: the following methods could be useful: `.groupby()`, `.agg()`, `.reset_index()`

In [ ]:
# Answer

continent_count = ...

**Question 2.5 (8 points)**: 

Now let's visualize the number of countries in each continent as a bar plot and a pie chart, next to each other on the same figure. To do this, please complete the following steps: 

1. On the left subplot, create a bar plot of the `continent_count` data, where there is one bar for each continent, and heights of the bars correspond to the number of countries in each continent. 

2. On the right subplot, create a pie chart, and be sure that each "piece of the pie" is labeled with the continent that it corresponds to. 

As always, be sure to [label your axes](https://flowingdata.com/wp-content/uploads/2012/06/label-your-axes.png) appropriately. Also, please make sure that none of the axes labels are overlapping, rotate the labels and/or extend the figure size to prevent them from overlapping (in general, try to make it look as good as you can!). This last, cosmetic part is the **one place in this homework** where you may look things up with Google or chatGPT - see the note at the top of the notebook. Everything else in this question must be your own work.

In [ ]:
# Answer:

# make the figure wider
...

# create the bar plot on the left subplot
...

# label the bar plot and rotate the axes
...

# Hide top and right spine (not necessary to do this)
...

# create the pie chart on the right subplot
...

**Question 2.6 (8 points)**: Continuing with our data visualization, let's now plot a histogram and a boxplot of the GDP per capita for the countries in our 2007 dataset next to each other on the same figure. To do this, please complete the following steps: 

1. On the left subplot, create a histogram of the GDP per capita. Make sure that the edgecolor of the bars in your histogram is black, and again make sure the graph is labeled appropriately. 

2. On the right subplot, create a boxplot of the same data.
  
Again adjust the figure size and other aspects of these plots to make them as good looking as you can. 

In the answer section, please describe what the advantages and disadvantages are of histograms vs. boxplots for visualizing quantitative data.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**: 

</font>

**Question 2.7 (4 points)**: Let's now create a simple scatter plot of life expectancy as a function of a country's GDP per capita using the `plt.plot()` function 

As always labeling your figure appropriately. In the answer section below, describe, in 1-3 sentences, the relationship between GDP per capita and life expectancy.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

**Question 2.8 (4 points)**: The plot of life expectancy as a function of a country's GDP per capita we created above shows some of the relationship between different variables in our data, but it is not as rich as the visualization created by Hans Rosling. Let's see if we can get closer to Hans' visualization.

What is missing from our visualization above is showing each country's population as the size of the points in the scatter plot, and each country's continent in a different color. Mapping the population size to a marker size is easy using the `plt.scatter()` function, but mapping each continent name to a color requires a little more work. 

To map each continent to a different color, let's start by creating a DataFrame called `continent_color_df`, that lists which color each continent should be shown as. In particular, the `continent_color_df` should have 5 rows (corresponding to each continent) and two columns which are:

1. `continent`: The name of each continent
2. `color`: A color that each continent should be shown as

To create the `continent_color_df`, start by creating a dictionary where the keys are called `continent` and `color` and the values are a list of continent names (in alphabetical order), and a list of colors in the order `['blue','green', 'red', 'orange', 'yellow']` (i.e., the first row of the `continent_color_df` should value the values `Africa` and `blue`, etc.).  

Once you have created this dictionary, use the `pd.DataFrame()` method to create the `continent_color_df` DataFrame and print it to show your work.

In [ ]:
# Answer

...

**Question 2.9 (4 points)**: Now that we have the `continent_color_df`, please create a DataFrame called `gapminder_2007_color` where you join (i.e., merge) the `continent_color_df` on to the `gapminder_2007` DataFrame. 

Display the first three rows `gapminder_2007_color` to show your work.

Hint: Use `.merge()` method and remember to specify which column you are merging on.

In [ ]:
# Answer

...

**Question 2.10 (6 points)**: Now we are ready to create a plot that is more similar to Hans'. To do this, use the `plt.scatter()` function with the following arguments: 

1. The x-axis variable should be GDP per capita (as before)
2. The y-axis variable should be life expectancy (as before)
3. The size of each point should be the country's population, in millions of people (i.e., divide the population size by $10^6$)
4. The color should be a country's continent color 
5. Also make the points transparent, with alpha set to .5, so that we can see overlapping points.

As always, label your axes! In the answer section, describe any information that is missing from your figure that would make it clearer.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

<div style="page-break-after: always;"></div>

## 3. Visual comparisons

For our next set of exercises, let's create plots where we explore different ways to compare quantities visually by examining data from New York City's Citi Bike program.

**Question 3.1 (2 points)**: New York City's Citi Bike Program is a bicycle sharing system where members can rent bikes at one location and return bikes at a different location. 

The data we will look at consists of information about how many trips were taken each day from July 1st 2013 until November 30th 2015. The DataFrame also contains information about the weather, and about whether each day is a weekday, weekend, holiday, etc. (if you are interested in data on individual bike trips see https://citibikenyc.com/system-data). 

The data is loaded below. As usual, start by printing the types of data that are contained in each column.

In [ ]:
bikes = pd.read_csv("daily_bike_totals.csv", parse_dates= [0])
bikes.head(3)

,date,trips,precipitation,snow_depth,snowfall,max_temperature,min_temperature,average_wind_speed,dow,year,month,holiday,stations_in_service,weekday,weekday_non_holiday
0,2013-07-01,16650,0.838583,0.0,0.0,77.00,71.96,3.13171,1,2013,7,False,NaN,True,True
1,2013-07-02,22745,0.078740,0.0,0.0,82.04,71.96,2.68432,2,2013,7,False,NaN,True,True
2,2013-07-03,21864,0.531496,0.0,0.0,82.94,73.04,4.25018,3,2013,7,False,NaN,True,True

In [ ]:
# Answer
# add a line of code to print the dtypes of the columns here
...

**Question 3.2 (4 points)**: To gain more experience with visualization, let's compare the number of trips taken on weekdays vs. weekends. 

To start this analysis, create a DataFrame called `weekday` which only has trips taken on weekdays, and a DataFrame called `weekend` which only has trips taken on weekends. 

Print the first 3 rows of the `weekend` DataFrame to show your work.

In [ ]:
# Answer

...

**Question 3.3 (5 points)**:  Now use the [plt.boxplot() function](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.boxplot.html) to create side-by-side box plots of the number of trips taken on weekdays and the number of trips taken on weekends. 

Be sure to put labels below each boxplot so that it is clear which boxplot corresponds to weekdays and weekends and also label your y-axis. 

In the answer section, in 2-5 sentences describe if it seems clear that more trips are taken on weekdays vs. weekends. In particular, imagine we had data from the next two years (i.e., July 1st 2016 until November 30th 2018). Does this plot give compelling evidence that we would see the same pattern with more trips on weekdays?

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

**Question 3.4 (5 points)**: Let's now create histograms of the data. In particular, create two subplots (one above the other) whether the upper plot shows a histogram of the number of trips taken on weekdays, and the lower plot shows a histogram of the number of trips taken on weekends. Be sure to label your plot to make everything as clear as possible!

In the answer section below, in 1-5 sentences describe whether you think this plot more clearly contrasts the number of trips taken on weekdays vs. weekends relative to plotting the data as boxplots.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

**Question 3.5 (4 points)**: Finally, let's create line plots of the data where we plot the number of trips as a function of the date for both weekdays and weekends (i.e., your plot should have two lines on it). As always, be sure to label all your plot fully! 

In the answer section, describe whether you think this plot more clearly contrasts the number of trips taken on weekdays vs. weekends relative to plotting the data as boxplots and histograms.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

<div style="page-break-after: always;"></div>

## 4. Visualizing the Gapminder data using seaborn

Let's now revisit visualizing the Gapminder data but this time using seaborn to create easier and better looking visualizations!

Again, we will focus on only the data from 2007, which you created above in the DataFrame `gapminder_2007`.

**Question 4.1 (4 points)**: For a first visualization using seaborn, please recreate the bar chart that shows how many countries are in each continent; i.e., there is one bar for each continent and the height of each bar is the number of countries in each continent. 

To do this you can use the `sns.catplot()` method, where the following arguments should be set:

- `data`: should be the `gapminder_2007` DataFrame
- `x` should be the appropriate label name from the `gapminder_2007` DataFrame
- `kind` should be set to `"count"`. 

To see a list of all the arguments (i.e., parameters) for `sns.catplot()`, please see the [seaborn documentation](https://seaborn.pydata.org/generated/seaborn.catplot.html)

As always, be sure to label your axes. Since seaborn is built on top of matplotlib, you can use the same `plt.` methods to set the axes (e.g., `plt.xlabel()` etc.).

In [ ]:
import seaborn as sns

In [ ]:
# Answer

...

**Question 4.2 (4 points)**: Continuing with our visualizations using seaborn, let's visualize the GDP per capita from all the countries in our 2007 dataset.

To do this, you can use the `sns.displot()` method. Experiment with the `kind` argument, and pick the value for the argument that you think gives the clearest pictures of how GDP per capita differs across different countries. In the answer section below, in 1-5 sentences, please justify your choice. 

Hint: the values that the `kind` argument can take are: `'hist'`, `'kde'`, or `'ecdf'`.

In [ ]:
# Answer

<font color='red'> **ANSWER**:

**Question 4.3 (4 points)**: Now let's visualize the life expectancy for the all the countries grouped by the continent the country is in. To do this we should use the `sns.catplot()` function which plots quantitative data as a function of a categorical variable. 

Please go ahead and create this plot, and again choose the value for the `kind` argument that you think makes the most sense. In the answer section, please explain why you think the value you choose for the `kind` argument creates the best plot.  

Hint: the values that the `kind` argument can take are: `“strip”`, `“swarm”`, `“box”`, `“violin”`, `“boxen”`, `“point”`, or `“bar”`.

In [ ]:
# Answer

<font color='red'> **ANSWER**:

**Question 4.4 (5 points)**: Let's now explore faceting by plotting GDP per capita as a function of the year with a separate subplot for each continent. In particular, please use `sns.catplot()` and the `gapminder` DataFrame (i.e., the DataFrame with data from all years) to create a plot that has the following features:

1. The x-axis should plot the year.
2. The y-axis should be the GDP per capita.
3. There should be a separate subplot/facet (as a column) for each continent.
4. There should be a maximum of 3 columns before the faceting is wrapped. We have not used the argument that does this in class - it is called `col_wrap`, and you should look it up in the [seaborn documentation](https://seaborn.pydata.org/generated/seaborn.catplot.html) to see what it takes. Looking up an argument in the documentation is a normal part of the work, and this is the one place in this homework where you need to. 
5. You should create boxplots for each year. 

In the answer section, please answer the following questions:

1. In 1-3 sentences, explain if the trends seen in the data make sense. 

2. Report if you notice any large outliers in plot and what they correspond to.

Hint: If you want to change the axis labels on a faceted plot, you need to save the plot to a name (such as the name `g`). You can then use `g.set(ylabel = "blah")` to set the y-label, etc.

In [ ]:
# Answer

<font color='red'> **ANSWER**:

**Question 4.5 (5 points)**: Now let's recreate a plot that this is similar to plots in Hans Rosling's video, where we plot life expectancy as a function of GDP per capita. Since we are plotting two quantitative variables, we should use seaborn's `sns.relplot()` with the following features:

1. The x-axis variable should be GDP per capita (as before)
2. The y-axis variable should be life expectancy (as before)
3. The size of each point should be the country's population
4. The color should be a country's continent color 
5. Also make the points transparent, with alpha set to .5, so that we can see overlapping points.

As in question 2.3, please only use data from 2007 for this plot. 

In the answer section, in 1-5 sentences, describe any features that are better and/or worse than the similar plot you created in question 2.7 and 2.10.

In [ ]:
# Answer

...

<font color='red'> **ANSWER**:

<div style="page-break-after: always;"></div>

## 5. Create your own visualization (5 points)

For the last part of the homework, please create a visualization of your own choosing. You can use one of the datasets we have previously used in class (e.g., the ACS data, squirrel data, etc), or you can find a new data set and plot it, which might be particularly useful to get started on your final project! If you want to use a new data set, a list of sources where you can find data can be found under the "Data sources" link on the left of the class Canvas page. 

You can also use either matplotlib or seaborn, or both. Please focus on making your figure as clear and beautiful as possible!

In the section below, give a brief description of what your image shows. Also, upload your image and image description to Canvas and we can share these as well in class.

In [ ]:
# Answer

<font color='red'> **ANSWER**:  Please describe what your image shows here

<div style="page-break-after: always;"></div>

## 6. Reflection (3 points)

Please reflect on how the homework went by going to Canvas, going to the Quizzes link, and clicking on reflection on homework 5.

<div style="page-break-after: always;"></div>

## 7. Submission

Once you're finished filling in and running all cells, you should submit your assignment as a .pdf on Gradescope. You can access Gradescope through Canvas on the left-side of the class home page. The problems in each homework assignment are numbered.

**NOTE:** When submitting on Gradescope, please select the correct pages of your pdf that correspond to each problem. <font color='red'>**Failure to mark pages correctly will result in points being deducted from your homework score.**</font>

**Do these four things in order:**

1. **Restart the kernel and run every cell**, top to bottom (Kernel → Restart Kernel and Run All Cells). This checks your work actually runs from a clean start.
2. <font color='red'>**Save your notebook**</font> (Ctrl-S, or Cmd-S on a Mac). The file is built from the *saved* notebook, so anything you have not saved will not appear in it.
3. **Run the cell below.** It creates an `.html` file next to this notebook — you may need to refresh the file browser on the left to see it.
4. **Download that `.html` file, open it in a web browser** (double-click it on your own computer), then **File → Print** and set the destination to **Save as PDF**. Upload that pdf to Gradescope.

<font color='red'>**Use File → Print. Do NOT use File → Export as PDF.**</font> Export produces a single very long page instead of ordinary numbered pages. That does not render properly in Gradescope, and it makes it impossible to mark which page each problem is on — which costs you points.

<font color='red'>**Please do not use File → Save and Export Notebook As… → HTML.**</font> That menu produces a file with the formatting stripped out and html tags printed through the text. Use the cell below instead.

If you open the `.html` file *inside* Jupyter you will see the page's code rather than the page — that is just how Jupyter displays html files, and it does not mean anything is wrong. Open it in a web browser.

Before you submit, **open the pdf and check that all your code and output are visible** — <font color='red'>**points are deducted for work we cannot see.**</font>

In [ ]:
import glob, os, pathlib, datetime
import nbformat
from nbconvert import HTMLExporter
from traitlets.config import Config

# Which notebook is this? Three ways, most reliable first.
# 1. Jupyter tells the kernel, via JPY_SESSION_NAME -> __session__. Survives a
#    rename, but is only set if the kernel was launched with a session, so it
#    is often missing and cannot be the only method.
_s = globals().get("__session__") or os.environ.get("JPY_SESSION_NAME")
_nb = pathlib.Path(_s).name if _s else None

# 2. The name this file was published under. nbbuild rewrites this string when
#    it builds the student copy, so each build looks for its own name. This is
#    what makes it work when the instructor has BOTH files in one folder.
_self = "homework_05.ipynb"
if not _nb or not pathlib.Path(_nb).exists():
    _nb = _self if pathlib.Path(_self).exists() else None

# 3. Last resort: exactly one plausible match beside us. Never fall back onto
#    the other build's file -- the instructor has homework_NN.ipynb and
#    homework_NN_answers.ipynb side by side, and exporting the wrong one
#    silently would be worse than failing.
if not _nb:
    _mine = _self.endswith("_answers.ipynb")
    _cand = [f for f in sorted(glob.glob("homework_05*.ipynb"))
             if "-checkpoint" not in f and f.endswith("_answers.ipynb") == _mine]
    _nb = _cand[0] if len(_cand) == 1 else None

# 4. Renamed to something unrecognisable, but there is only one notebook here,
#    so it must be this one.
if not _nb:
    _only = [f for f in sorted(glob.glob("*.ipynb")) if "-checkpoint" not in f]
    _nb = _only[0] if len(_only) == 1 else None

if not _nb:
    print("Could not work out which notebook this is.")
    print("Notebooks in this folder:", sorted(glob.glob("*.ipynb")))
    print('Set it by hand and re-run, e.g.   _nb = "my_file.ipynb"')
else:
    _html  = pathlib.Path(_nb).with_suffix(".html")
    _saved = datetime.datetime.fromtimestamp(pathlib.Path(_nb).stat().st_mtime)
    _cfg = Config()
    _cfg.TagRemovePreprocessor.remove_input_tags = ("hide-export",)
    _cfg.TagRemovePreprocessor.enabled = True
    _cfg.HTMLExporter.preprocessors = ["nbconvert.preprocessors.TagRemovePreprocessor"]
    try:
        _exp = HTMLExporter(config=_cfg, template_name="lab")
    except Exception:
        _exp = HTMLExporter(config=_cfg)
    # The Save-and-Export menu sets this True, which escapes the html and strips
    # the page breaks. Doing the export here keeps it off.
    _exp.sanitize_html = False
    try:
        _body, _ = _exp.from_notebook_node(nbformat.read(_nb, as_version=4))
        _html.write_text(_body, encoding="utf-8")
        print(f"Created {_html.name}  ({_html.stat().st_size // 1024} KB)")
        print(f"Built from {_nb}, as SAVED at {_saved:%H:%M:%S}.")
        print("If you have run any cells since then, save and run this cell again.")
        print()
        print("Now download this .html file, open it in a web browser,")
        print("then File -> Print -> Save as PDF, and upload the pdf to Gradescope.")
    except Exception as _err:
        print("The html was NOT created. The error is below.")
        print(repr(_err)[:500])